**Álgebra Matricial no Python**

Principais comandos do pacote *numpy*:

- Criação de matriz: np.array([[x11, x12, x13], [x21, x22, x23]])
- Dimensão de uma matriz: matriz.shape
- Criação de matriz de zeros: np.zeros((nl, nc))
- Criação de matriz de 1s: np.ones((nl, nc))
- Matriz identidade: np.identity(n)
- Matriz transposta: matriz.T
- Vetor com uma sequência de números: np.arange(n)
- Vetor a partir de sequência (início, fim, intervalo):
np.arange(início, fim, intervalo)
- Mudar o formato de uma matriz: matriz.reshape(nl, nc)
- Produto de Hadamard: A * B
- Multiplicação de matrizes: A @ B
- Posto: np.linalg.matrix_rank(matriz)
- Determinante: np.linalg.det(matriz)
- Traço: np.trace(matriz)
- Inversa clássica: np.linalg.inv(matriz)
- Inversa generalizada: np.linalg.pinv(matriz)

Obs.: nl = número de linhas; nc = número de colunas

In [ ]:
# pacote necessário para operações vetoriais e matriciais
import numpy as np

Criação de vetores e matrizes

In [ ]:
a = np.array([2, 3, 4])

In [ ]:
a

array([2, 3, 4])

In [ ]:
print(a)

[2 3 4]


In [ ]:
# formato
a.shape

(3,)

In [ ]:
# tipo
a.dtype

dtype('int64')

In [ ]:
a.ndim

1

In [ ]:
b = np.array([1.2, 3.5, 5])
print(b)

[1.2 3.5 5. ]


In [ ]:
b.dtype

dtype('float64')

In [ ]:
# matriz
B = np.array([[1.5, 2, 3], [4, 5, 6]])
print(B)

[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [ ]:
B.shape

(2, 3)

Matriz de zeros:

In [ ]:
np.zeros((1, 2))

array([[0., 0.]])

Matriz de 1s:

In [ ]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

Matriz identidade $\boldsymbol{I}$:

In [ ]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Vetor com valores a partir de uma sequência:

In [ ]:
# vetor a partir de sequência (início, fim, intervalo)


In [ ]:
# mudar o formato da matriz


**Operações elementares**

In [ ]:
a = np.arange(3)

In [ ]:
b = np.array([2, 5, 6])

In [ ]:
print(a, b)

[0 1 2] [2 5 6]


In [ ]:
# soma dos vetores a e b
a + b

array([2, 6, 8])

Soma de matrizes

In [ ]:
A = np.arange(6).reshape(2, 3)
B = np.array([[1, 2, 3.4], [4, 5.7, 8]])
print(A)
print(B)

[[0 1 2]
 [3 4 5]]
[[1.  2.  3.4]
 [4.  5.7 8. ]]


In [ ]:
A + B

array([[ 1. ,  3. ,  5.4],
       [ 7. ,  9.7, 13. ]])

Produto de Hadamard

In [ ]:
A * B

array([[ 0. ,  2. ,  6.8],
       [12. , 22.8, 40. ]])

Multiplicação de matrizes

In [ ]:
# multiplicação de matrizes
A @ B

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

Qual o problema com essa multiplicação?

In [ ]:
C = np.arange(6).reshape(3, 2)
print(C)
print(A)

[[0 1]
 [2 3]
 [4 5]]
[[0 1 2]
 [3 4 5]]


In [ ]:
# produto de C por A
C @ A

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [ ]:
np.dot(C, A)

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

Transposta de uma matriz:

In [ ]:
np.transpose(C)

array([[0, 2, 4],
       [1, 3, 5]])

In [ ]:
# produto


Posto de uma matriz:

In [ ]:
G = np.array([[7, 13, 1, 12], [20, 3, 14, 7], [4, 15, 4, 2], [4, 18, 1, 1]])
G

array([[ 7, 13,  1, 12],
       [20,  3, 14,  7],
       [ 4, 15,  4,  2],
       [ 4, 18,  1,  1]])

In [ ]:
# obter o posto de G
np.linalg.matrix_rank(G)

np.int64(4)

Determinante:

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 4], [3, 2, 1]])
print(A)

[[1 2 3]
 [4 5 4]
 [3 2 1]]


In [ ]:
# determinante de A
np.linalg.det(A)

np.float64(-7.999999999999998)

Traço:

In [ ]:
np.trace(A)

np.int64(7)

Inversa clássica:

In [ ]:
np.linalg.inv(A)

array([[ 0.375, -0.5  ,  0.875],
       [-1.   ,  1.   , -1.   ],
       [ 0.875, -0.5  ,  0.375]])

Lembrando que a definição de inversa é:

Para matrizes quadradas,

\begin{equation}
  \textbf{A}^{-1}\textbf{A} = \textbf{I} =  \textbf{A}\textbf{A}^{-1}
\end{equation}


Verificar a definição para:

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 4], [3, 2, 1]])

In [ ]:
A1 = np.linalg.inv(A)
A1

array([[ 0.375, -0.5  ,  0.875],
       [-1.   ,  1.   , -1.   ],
       [ 0.875, -0.5  ,  0.375]])

In [ ]:
A1 @ A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# A1 @ A é igual a I?
np.allclose(A1 @ A, I)

True

In [ ]:
# A @ A1 é igual a I?
np.allclose(A @ A1, I)

True

Inversa generalizada (para os casos em que não é possível obter a inversa clássica):

In [ ]:
Am = np.linalg.pinv(A)
Am

array([[ 0.375, -0.5  ,  0.875],
       [-1.   ,  1.   , -1.   ],
       [ 0.875, -0.5  ,  0.375]])

**Decomposição espectral: autovalores e autovetores já apresentados de forma ordenada**

In [ ]:
A = np.array([[8, -2], [-2, 5]])

In [ ]:
l, e = np.linalg.eig(A)
idx = np.argsort(l)[::-1]
l = l[idx]
e = e[:, idx]
print(l)
print(e)

[9. 4.]
[[ 0.89442719  0.4472136 ]
 [-0.4472136   0.89442719]]


Matriz **$\Lambda$**:

In [ ]:
L = np.diag(l)
L

array([[9., 0.],
       [0., 4.]])

Matriz **$P$**:

In [ ]:
P = e

Outras decomposições de matrizes:

In [ ]:
A = np.array([[8, -2], [-2, 5]])
A

array([[ 8, -2],
       [-2,  5]])

In [ ]:
# cholesky
np.linalg.cholesky(A)

array([[ 2.82842712,  0.        ],
       [-0.70710678,  2.12132034]])

In [ ]:
# QR
np.linalg.qr(A)

QRResult(Q=array([[-0.9701425 ,  0.24253563],
       [ 0.24253563,  0.9701425 ]]), R=array([[-8.24621125,  3.15296313],
       [ 0.        ,  4.36564125]]))

In [ ]:
# SVD
np.linalg.svd(A)

SVDResult(U=array([[-0.89442719,  0.4472136 ],
       [ 0.4472136 ,  0.89442719]]), S=array([9., 4.]), Vh=array([[-0.89442719,  0.4472136 ],
       [ 0.4472136 ,  0.89442719]]))

## Observação sobre autovalores e matrizes ortogonais

Matriz ortogonal é uma matriz em que as seguintes relações valem:

$\boldsymbol{Q}^T \boldsymbol{Q} =     \boldsymbol{Q}\boldsymbol{Q}^T = \boldsymbol{I}$

$\boldsymbol{Q}^T = \boldsymbol{Q}^{-1}$

$|{\boldsymbol{Q}}| = \pm 1$

Vimos, em autovalores e autovetores, que:

se $\textbf{A}$ é ortogonal, $\lambda_i = \pm 1$

Então, se os autovalores de uma matriz forem $\lambda_i = \pm 1$ significa que ela é ortogonal?

Seja
\begin{align*}
		\boldsymbol{A} =
		\left[
		\begin{array}{cc}
		1 & 1 \\
		0 & -1 \\
		\end{array}
		\right].
\end{align*}

Verifique a suposição.

$\lambda_i = \pm 1$:

Verificar se $\boldsymbol{A}$ é ortogonal:

$\boldsymbol{A}^T \boldsymbol{A} =     \boldsymbol{A}\boldsymbol{A}^T = \boldsymbol{I}$


$\boldsymbol{A}^T = \boldsymbol{A}^{-1}$

Conclusão?