## Numpy: _Numeric computing library_

NumPy (Numerical Python) é um dos principais pacotes para computação numérica em Python. Pandas, Matplotlib, Statmodels e muitas outras bibliotecas científicas rodam em cima de NumPy.

As principais contribuições dessa _librarie_ são:

- Computação numérica eficiente com _C primitives_.
- Coleções eficientes com operações vetorizadas.
- Uma API de Algebra Linear natural e integrada.
- Uma API de C para conectar NumPy com bibliotecas escritas em C, C++, ou FORTRAN.

Em Python, **tudo é um objeto**, o que significa que simples números inteiros também são objetos, com toda a maquinaria e carcaça necessária para um objeto funcionar propriamente. Eles são chamados de "_Boxed Ints_". Em contrapartida, NumPy utiliza tipos numéricos primitivos (floats, ints), o que torna o armazenamento e a computação mais eficiente.

![Numpy](/images/numpy.png)

### Hands on!

In [2]:
import sys
import numpy as np

### Basic Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [6]:
b = np.array([0, .5, 1, 1.5, 2])

In [7]:
a[0], a[1]

(1, 2)

In [8]:
a[0:]

array([1, 2, 3, 4])

In [9]:
a[1:3]

array([2, 3])

In [10]:
a[::2]

array([1, 3])

In [11]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [12]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [14]:
b[[0, 2, -1]]

array([0., 1., 2.])

### Arrays Types:

In [15]:
a

array([1, 2, 3, 4])

In [16]:
a.dtype

dtype('int32')

In [17]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
b.dtype

dtype('float64')

In [20]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [21]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [22]:
c = np.array(['a', 'b', 'c'])

In [23]:
c.dtype

dtype('<U1')

In [24]:
d = np.array([{'a': 1}, sys])

In [25]:
d.dtype

dtype('O')

### Dimensions and shapes

In [26]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [27]:
A.shape # linhas e colunas

(2, 3)

In [28]:
A.ndim # quantas dimensões

2

In [29]:
A.size # tamanho

6

In [30]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])
# array tridimensional

In [31]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [32]:
B.shape # linhas e colunas

(2, 2, 3)

In [33]:
B.ndim # dimensões

3

In [34]:
B.size

12

### Indexing and Slicing of Matrices

In [35]:
# Square matrix
A = np.array([
#.   0. 1. 2.
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [36]:
A[1]

array([4, 5, 6])

In [37]:
A[1][0]  # A[row][column]

4

In [38]:
A[1, 0] # A[d1, d2, d3, d4]

4

In [39]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
A[:, :2] # de todas as linhas, extraia os valores até a coluna 2

array([[1, 2],
       [4, 5],
       [7, 8]])

In [41]:
A[:2, :2] # até a linha 2, extraia os valores até a coluna 2

array([[1, 2],
       [4, 5]])

In [42]:
A[:2, 2:] # até a linha 2, extraia os valores a partir da coluna 2

array([[3],
       [6]])

In [43]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
A[1] = np.array([10, 10, 10])

In [45]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [46]:
A[2] = 99

In [47]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

### Summary Statistics:

In [48]:
a = np.array([1, 2, 3, 4])

In [49]:
a.sum()

10

In [50]:
a.mean()

2.5

In [51]:
a.std()

1.118033988749895

In [52]:
a.var()

1.25

In [53]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [54]:
A.sum()

45

In [55]:
A.mean()

5.0

In [56]:
A.std()

2.581988897471611

In [57]:
A.sum(axis=0)

array([12, 15, 18])

In [58]:
A.sum(axis=1)

array([ 6, 15, 24])

In [59]:
A.mean(axis=0)

array([4., 5., 6.])

In [60]:
A.mean(axis=1)

array([2., 5., 8.])

In [61]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [62]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

### Broadcasting and Vectorized Operations:

In [3]:
a = np.arange(4)

In [4]:
a

array([0, 1, 2, 3])

In [5]:
a + 10

array([10, 11, 12, 13])

In [6]:
a * 10

array([ 0, 10, 20, 30])

In [7]:
a 

array([0, 1, 2, 3])

In [8]:
a += 100

In [9]:
a

array([100, 101, 102, 103])

In [10]:
l = [0, 1, 2, 3]

In [11]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [12]:
a = np.arange(4)

In [13]:
a

array([0, 1, 2, 3])

In [14]:
b = np.array([10, 10, 10, 10])

In [15]:
b

array([10, 10, 10, 10])

In [16]:
a + b

array([10, 11, 12, 13])

In [17]:
a * b

array([ 0, 10, 20, 30])

### Boolean arrays:

In [ ]:
a = np.arange(4)

In [19]:
a

array([0, 1, 2, 3])

In [20]:
a[0], a[-1]

(0, 3)

In [21]:
a[[0, -1]]

array([0, 3])

In [22]:
a[[True, False, False, True]]

array([0, 3])

In [23]:
a

array([0, 1, 2, 3])

In [24]:
a >= 2

array([False, False,  True,  True])

In [25]:
a[a >= 2]

array([2, 3])

In [26]:
a.mean()

1.5

In [28]:
a[a > a.mean()]

array([2, 3])

In [27]:
a[~ (a > a.mean())] # números que são menores do que a média

array([0, 1])

In [30]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [31]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [34]:
A = np.random.randint(100, size=(3, 3))

In [35]:
A

array([[77,  4,  2],
       [ 6, 39, 53],
       [52, 21, 62]])

In [36]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([77,  2, 39, 52, 62])

In [37]:
A > 30

array([[ True, False, False],
       [False,  True,  True],
       [ True, False,  True]])

In [38]:
A[A > 30]

array([77, 39, 53, 52, 62])

### Linear Algebra

In [40]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [41]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [42]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [43]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [44]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [45]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])