# Module: NumPy Assignments
## Lesson: NumPy

### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np

# Crate a NumPy array of shape(5,5) filled with random integers
array = np.random.randint(1, 21, size=(5, 5))
print('Original Array: ')
print(array)

print()

# Replace all the elements in the third column with 1
array[:, 2] = 1
print('Modified array: ')
print(array)

Original Array: 
[[ 8  2 20  8  6]
 [19  5 11 19  1]
 [ 2 13 18 14  2]
 [ 1 12 19  5  5]
 [ 8  7  8 19  6]]

Modified array: 
[[ 8  2  1  8  6]
 [19  5  1 19  1]
 [ 2 13  1 14  2]
 [ 1 12  1  5  5]
 [ 8  7  1 19  6]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [4]:
# Create a Numpy array of shape(4, 4) with values from 1 to 16
array = np.arange(1, 17).reshape((4, 4))
print('Original array: ')
print(array)

print()

# Replace the diagonal elements with 0
np.fill_diagonal(array, 0)
print('Modified array: ')
print(array)

Original array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Modified array: 
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [5]:
# Create a NumPy array of shape (6, 6) with values from 1 to 36
array = np.arange(1, 37).reshape((6 ,6))
print('Original array: ')
print(array)

print()

# Extract the sub-array
sub_array = array[2:5, 1:4]
print('Sub-array: ')
print(sub_array)

Original array: 
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Sub-array: 
[[14 15 16]
 [20 21 22]
 [26 27 28]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [19]:
# Create a NumPy array of shape(5, 5) with random integers
array = np.random.randint(1, 21, size=(5, 5))
print('Original array: ')
print(array)

print()

# Extract the elements on the border
border_elements = np.concatenate((array[0, :], array[-1, :], array[1:-1, 0], array[1:-1, -1])).reshape(4, 4)
print('Border elements: ')
print(border_elements)

Original array: 
[[19 12  9 10  3]
 [12  3 16 20 15]
 [20  6  1 10 17]
 [18  5  4 14  7]
 [12  7  3  9  9]]

Border elements: 
[[19 12  9 10]
 [ 3 12  7  3]
 [ 9  9 12 20]
 [18 15 17  7]]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [21]:
# Create two NumPy arrays of shape(3, 4) filled with random integers
array1 = np.random.randint(1, 11, size=(3, 4))
array2 = np.random.randint(1, 11, size=(3, 4))

print('Array 1: ')
print(array1)
print()
print('Array 2: ')
print(array2)

# Perform elemnent-wise operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print()

print("Element-wise addition:")
print(addition)
print("Element-wise subtraction:")
print(subtraction)
print("Element-wise multiplication:")
print(multiplication)
print("Element-wise division:")
print(division)

Array 1: 
[[ 7  7  4  4]
 [ 7 10  1  5]
 [10  6  6  6]]

Array 2: 
[[7 1 4 3]
 [5 2 6 9]
 [2 8 8 5]]

Element-wise addition:
[[14  8  8  7]
 [12 12  7 14]
 [12 14 14 11]]
Element-wise subtraction:
[[ 0  6  0  1]
 [ 2  8 -5 -4]
 [ 8 -2 -2  1]]
Element-wise multiplication:
[[49  7 16 12]
 [35 20  6 45]
 [20 48 48 30]]
Element-wise division:
[[1.         7.         1.         1.33333333]
 [1.4        5.         0.16666667 0.55555556]
 [5.         0.75       0.75       1.2       ]]


2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1

2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.