### NumPy Exercises

In [2]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.26.4


### Array Creation

#### Create a numpy array of size 10, filled with zeros.

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create a numpy array with values ranging from 10 to 49

In [4]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create a numpy matrix of 2*2 integers, filled with ones.

In [5]:
np.ones([2, 2], dtype=np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

#### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [6]:
np.ones([3, 2], dtype=np.float32)

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

#### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [7]:
X = np.arange(4, dtype=np.int64)

np.ones_like(X)

array([1, 1, 1, 1], dtype=int64)

#### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [8]:
X = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64)

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

#### Create a numpy matrix of 4*4 integers, filled with fives.

In [9]:
np.ones([4, 4], dtype=np.int64) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int64)

#### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [10]:
X = np.array([[2,3], [6,2]], dtype=np.int64)

np.ones_like(X) * 7

array([[7, 7],
       [7, 7]], dtype=int64)

#### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [11]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Create a numpy array, filled with 3 random integer values between 1 and 10

In [12]:
np.random.randint(10, size=3)

array([1, 8, 3])

#### Create a 3 * 3 * 3 numpy matrix, filled with random float values.

In [13]:
np.random.random((3, 3, 3))

array([[[0.92769845, 0.19646892, 0.1149271 ],
        [0.61199945, 0.45269566, 0.0521289 ],
        [0.65666745, 0.23982326, 0.89673913]],

       [[0.22939896, 0.27567721, 0.10138844],
        [0.76629806, 0.45876631, 0.51433985],
        [0.71680807, 0.75247327, 0.6294448 ]],

       [[0.28191819, 0.12679898, 0.9755251 ],
        [0.37977327, 0.63025087, 0.52494096],
        [0.10454481, 0.43596636, 0.0676089 ]]])

#### Given the X python list convert it to an Y numpy array.

In [14]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


#### Given the X numpy array, make a copy and store it on Y.

In [15]:
X = np.array([5, 2, 3], dtype=np.int64)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y))

[5 2 3] 1888574441392
[5 2 3] 1888574443024


#### Create a numpy array with numbers from 1 to 10.

In [16]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Create a numpy array with the odd numbers between 1 to 10.

In [17]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

#### Create a numpy array with numbers from 1 to 10, in descending order.

In [18]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8.

In [19]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Show the memory size of the given Z numpy matrix.

In [20]:
Z = np.zeros((10,10))

print(f'{Z.size *  Z.itemsize} bytes')

800 bytes


### Array Indexation

#### Given the X numpy array, show it's first element.

In [21]:
X = np.array(['A','B','C','D','E'])

X[0]

'A'

#### Given the X numpy array, show it's last element

In [22]:
X = np.array(['A','B','C','D','E'])

X[-1]

'E'

#### Given the X numpy array, show it's first three elements

In [24]:
X = np.array(['A','B','C','D','E'])

X[0:3]

array(['A', 'B', 'C'], dtype='<U1')

#### Given the X numpy array, show all middle elements

In [25]:
X = np.array(['A','B','C','D','E'])

X[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

#### Given the X numpy array, show the elements in reverse position

In [27]:
X = np.array(['A','B','C','D','E'])

X[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

#### Given the X numpy array, show the elements in an odd position

In [28]:
X = np.array(['A','B','C','D','E'])

X[::2]

array(['A', 'C', 'E'], dtype='<U1')

#### Given the X numpy matrix, show the first row elements

In [30]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0]

array([1, 2, 3, 4])

#### Given the X numpy matrix, show the last row elements

In [31]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1]

array([13, 14, 15, 16])

#### Given the X numpy matrix, show the first element on first row

In [32]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[0][0]

1

#### Given the X numpy matrix, show the last element on last row

In [33]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1][-1]

16

#### Given the X numpy matrix, show the middle row elements

In [35]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[1:-1, 1:-1]

array([[ 6,  7],
       [10, 11]])

#### Given the X numpy matrix, show the first two elements on the first two rows

In [37]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[:2, :2]

array([[1, 2],
       [5, 6]])

#### Given the X numpy matrix, show the last two elements on the last two rows

In [38]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[2:, 2:]

array([[11, 12],
       [15, 16]])

### Array Manipulation

#### Convert the given integer numpy array to float

In [39]:
X = [-5, -3, 0, 10, 40]

np.array(X, np.float64)

array([-5., -3.,  0., 10., 40.])

#### Reverse the given numpy array (first element becomes last)

In [40]:
X = [-5, -3, 0, 10, 40]

X[::-1]

[40, 10, 0, -3, -5]

#### Order (sort) the given numpy array

In [41]:
X = [0, 10, -5, 40, -3]

X.sort()
X

[-5, -3, 0, 10, 40]

#### Given the X numpy array, set the fifth element equal to 1

In [42]:
X = np.zeros(10)

X[4] = 1
X

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Given the X numpy matrix, change the last row with all 1

In [44]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1] = 1
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  1,  1,  1]])

#### Given the X numpy matrix, change the last item on the last row with a 0

In [45]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])

X[-1, -1] = 0
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15,  0]])

### Boolean Arrays

#### Given the X numpy array, make a mask showing negative elements

In [46]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])

mask = X < 0
mask

array([ True, False, False,  True, False, False, False, False,  True,
       False])

#### Given the X numpy array, get the negative elements

In [47]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X < 0
X[mask]

array([-1, -4, -9])

#### Given the X numpy array, get numbers higher than 5

In [48]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > 5
X[mask]

array([ 6, 10])

#### Given the X numpy array, get numbers higher than the elements mean

In [49]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = X > X.mean()
X[mask]

array([ 2,  5,  6, 10])

#### Given the X numpy array, get numbers equal to 2 or 10

In [50]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])

mask = (X == 2) | (X == 10)
X[mask]

array([ 2, 10])