## Numpy: _Numeric computing library_

NumPy (Numerical Python) é um dos principais pacotes para computação numérica em Python. Pandas, Matplotlib, Statmodels e muitas outras bibliotecas científicas rodam em cima de NumPy.

As principais contribuições dessa _librarie_ são:

- Computação numérica eficiente com _C primitives_.
- Coleções eficientes com operações vetorizadas.
- Uma API de Algebra Linear natural e integrada.
- Uma API de C para conectar NumPy com bibliotecas escritas em C, C++, ou FORTRAN.

Em Python, **tudo é um objeto**, o que significa que simples números inteiros também são objetos, com toda a maquinaria e carcaça necessária para um objeto funcionar propriamente. Eles são chamados de "_Boxed Ints_". Em contrapartida, NumPy utiliza tipos numéricos primitivos (floats, ints), o que torna o armazenamento e a computação mais eficiente.

![Numpy](/images/numpy.png)

### Hands on!

In [1]:
import sys
import numpy as np

### Basic Numpy Arrays

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [6]:
b = np.array([0, .5, 1, 1.5, 2])

In [7]:
a[0], a[1]

(1, 2)

In [8]:
a[0:]

array([1, 2, 3, 4])

In [9]:
a[1:3]

array([2, 3])

In [10]:
a[::2]

array([1, 3])

In [11]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [12]:
b[0], b[2], b[-1]

(0.0, 1.0, 2.0)

In [14]:
b[[0, 2, -1]]

array([0., 1., 2.])

### Arrays Types:

In [15]:
a

array([1, 2, 3, 4])

In [16]:
a.dtype

dtype('int32')

In [17]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [18]:
b.dtype

dtype('float64')

In [20]:
np.array([1, 2, 3, 4], dtype=np.float64)

array([1., 2., 3., 4.])

In [21]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [22]:
c = np.array(['a', 'b', 'c'])

In [23]:
c.dtype

dtype('<U1')

In [24]:
d = np.array([{'a': 1}, sys])

In [25]:
d.dtype

dtype('O')

### Dimensions and shapes

In [26]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [27]:
A.shape

(2, 3)

In [28]:
A.ndim

2

In [29]:
A.size

6