### NumPy Exercises

In [1]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.26.4


### Array Creation

#### Create a numpy array of size 10, filled with zeros.

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create a numpy array with values ranging from 10 to 49

In [4]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create a numpy matrix of 2*2 integers, filled with ones.

In [7]:
np.ones([2, 2], dtype=np.int8)

array([[1, 1],
       [1, 1]], dtype=int8)

#### Create a numpy matrix of 3*2 float numbers, filled with ones.

In [8]:
np.ones([3, 2], dtype=np.float32)

array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)

#### Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [9]:
X = np.arange(4, dtype=np.int64)

np.ones_like(X)

array([1, 1, 1, 1], dtype=int64)

#### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [11]:
X = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64)

np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

#### Create a numpy matrix of 4*4 integers, filled with fives.

In [12]:
np.ones([4, 4], dtype=np.int64) * 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]], dtype=int64)

#### Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [15]:
X = np.array([[2,3], [6,2]], dtype=np.int64)

np.ones_like(X) * 7

array([[7, 7],
       [7, 7]], dtype=int64)

#### Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Create a numpy array, filled with 3 random integer values between 1 and 10

In [17]:
np.random.randint(10, size=3)

array([4, 0, 8])

#### Create a 3 * 3 * 3 numpy matrix, filled with random float values.

In [19]:
np.random.random((3, 3, 3))

array([[[0.73718774, 0.7704821 , 0.4943221 ],
        [0.53874282, 0.88803474, 0.52028307],
        [0.93943079, 0.54262551, 0.21636157]],

       [[0.55055839, 0.54630331, 0.44326473],
        [0.89837434, 0.39314924, 0.45575027],
        [0.60601643, 0.10021777, 0.2191428 ]],

       [[0.71004296, 0.1824891 , 0.16544905],
        [0.01989886, 0.47839631, 0.41021225],
        [0.78225785, 0.87109843, 0.4069516 ]]])

#### Given the X python list convert it to an Y numpy array.

In [20]:
X = [1, 2, 3]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y)) # different type

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


#### Given the X numpy array, make a copy and store it on Y.

In [21]:
X = np.array([5, 2, 3], dtype=np.int64)
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y))

[5 2 3] 1400773191088
[5 2 3] 1400775057808


#### Create a numpy array with numbers from 1 to 10.

In [22]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Create a numpy array with the odd numbers between 1 to 10.

In [23]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

#### Create a numpy array with numbers from 1 to 10, in descending order.

In [24]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

#### Create a 3*3 numpy matrix, filled with values ranging from 0 to 8.

In [25]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Show the memory size of the given Z numpy matrix.

In [27]:
Z = np.zeros((10,10))

print(f'{Z.size *  Z.itemsize} bytes')

800 bytes


### Array Indexation

#### Given the X numpy array, show it's first element.