In [1]:
import numpy as np

### 1. Essa matriz é idempotente? Ela é ortogonal?

\begin{bmatrix}
3 & -6 \\
1 & -2
\end{bmatrix}

In [2]:
A = np.array([3, -6, 1, -2]).reshape((2, 2))
A

array([[ 3, -6],
       [ 1, -2]])

In [3]:
# verificando se é idempotente
np.allclose(A @ A, A)

True

In [4]:
# verificando se é ortogonal
np.allclose(A.T @ A, np.identity(2))

False

Portanto, a matriz A não é idempotente nem ortogonal.

### 2. A matriz abaixo é ortogonal?

\begin{bmatrix}
2 & 4 & 6 \\
1 & 3 & -5 \\
-2 & 7 & 9
\end{bmatrix}

In [5]:
B = np.array([2, 4, 6, 1, 3, -5, -2, 7, 9]).reshape((3, 3))
B

array([[ 2,  4,  6],
       [ 1,  3, -5],
       [-2,  7,  9]])

In [6]:
# verificando se é ortogonal
np.allclose(B.T @ B, np.identity(3))

False

Assim, podemos concluir que a matriz B não é ortogonal.

### 3. Qual o determinante dessa matriz?

\begin{bmatrix}
2 & 4 & 6 \\
1 & 3 & -5 \\
-2 & 7 & 9
\end{bmatrix}

In [7]:
B

array([[ 2,  4,  6],
       [ 1,  3, -5],
       [-2,  7,  9]])

In [8]:
print(f'O determinante da matriz B é: ~{np.linalg.det(B):.2f}')

O determinante da matriz B é: ~206.00


### 4. Qual a inversa da matriz abaixo?

\begin{bmatrix}
1 & 0 & 1 \\
1 & 0 & 0 \\
2 & 1 & 1
\end{bmatrix}

In [9]:
C = np.array([1, 0, 1, 1, 0, 0, 2, 1, 1]).reshape((3, 3))
C

array([[1, 0, 1],
       [1, 0, 0],
       [2, 1, 1]])

In [10]:
print(f'A inversa da matriz C é:\n{np.linalg.inv(C)}')

A inversa da matriz C é:
[[ 0.  1.  0.]
 [-1. -1.  1.]
 [ 1. -1.  0.]]


### 5. Obtenha o determinante de:

\begin{bmatrix}
1 & 1 \\
2 & 3
\end{bmatrix}


In [11]:
D = np.array([1, 1, 2, 3]).reshape((2, 2))
D

array([[1, 1],
       [2, 3]])

In [12]:
print(f'O determinante da matriz D é: {np.linalg.det(D)}')

O determinante da matriz D é: 1.0


### 6. Quais matrizes abaixo não são singulares (admitem inversa)?

In [13]:
A = np.array([3, 5, 9, 0, 3, 1]).reshape((2, 3))
B = np.array([1, 2, 3, 4]).reshape((2, 2))
C = np.array([8, 6, 4, 1, 1, 1, 4, 3, 2]).reshape(3, 3)
I5 = np.identity(5)

matrizes = {'A': A, 'B': B, 'C': C, 'I5': I5}

for nome, matriz in matrizes.items():
  try:
    if np.linalg.det(matriz) != 0:
      print(f'A matriz {nome} não é singular.')
    else:
      print(f'A matriz {nome} é singular.')
  except:
    print(f'A matriz {nome} é singular.')

A matriz A é singular.
A matriz B não é singular.
A matriz C é singular.
A matriz I5 não é singular.


### 7. Para as matrizes não singulares da questão 6, informe as inversas:

In [14]:
np.linalg.inv(B)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [15]:
np.linalg.inv(I5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 8. Informe os postos das matrizes abaixo:

In [16]:
L = np.array([-2, -2, 1, 1]).reshape((2, 2))
E = np.array([1, -4, -9, 8]).reshape((2, 2))
G = np.array([-1, 1, 1, -1]).reshape((2, 2))
K = np.array([7, 9, 1, 1]).reshape((2, 2))

In [17]:
print(L)
print(f'O posto da matriz L é: {np.linalg.matrix_rank(L)}')

[[-2 -2]
 [ 1  1]]
O posto da matriz L é: 1


In [18]:
print(E)
print(f'O posto da matriz E é: {np.linalg.matrix_rank(E)}')

[[ 1 -4]
 [-9  8]]
O posto da matriz E é: 2


In [19]:
print(G)
print(f'O posto da matriz G é: {np.linalg.matrix_rank(G)}')

[[-1  1]
 [ 1 -1]]
O posto da matriz G é: 1


In [20]:
print(K)
print(f'O posto da matriz K é: {np.linalg.matrix_rank(K)}')

[[7 9]
 [1 1]]
O posto da matriz K é: 2


### 9. Seja a seguinte matriz quadrada 2x2:

In [21]:
A = np.array([4, 2, 2, 5]).reshape((2, 2))
A

array([[4, 2],
       [2, 5]])

a. Quais são os autovalores associados à matriz A?

In [22]:
l, e = np.linalg.eig(A)
idx = np.argsort(l)[::-1]
l = l[idx]
e = e[:, idx]

In [23]:
print(l)

[6.56155281 2.43844719]


b.

In [24]:
# traço == soma dos autovalores
print(f'Traço de A: {np.trace(A)}')
print(f'Soma dos autovalores: {np.sum(l)}')
print(f'Portanto: {np.allclose(np.trace(A), np.sum(l))}')

Traço de A: 9
Soma dos autovalores: 9.0
Portanto: True


In [25]:
# det(A) == produtório do autovalores
print(f'Determinante de A: {np.linalg.det(A)}')
print(f'Produto dos autovalores: {np.prod(l)}')
print(f'Portanto: {np.allclose(np.linalg.det(A), np.prod(l))}')

Determinante de A: 15.999999999999998
Produto dos autovalores: 16.0
Portanto: True


In [26]:
# posto(A) == número de autovalores diferentes de zero
print(f'Posto de A: {np.linalg.matrix_rank(A)}')
print(f'Número de elementos de autovalores diferentes de zero: {np.count_nonzero(l)}')
print(f'Portanto: {np.allclose(np.linalg.matrix_rank(A), np.count_nonzero(l))}')

Posto de A: 2
Número de elementos de autovalores diferentes de zero: 2
Portanto: True


In [27]:
# A é singular se um autovalor é igual a zero
print(f'A matriz A é singular? {np.any(l) == 0}')

A matriz A é singular? False


### 10. Encontre as matrizes A e P associadas à seguinte matriz:

\begin{bmatrix}
3 & 0 \\
8 & -1
\end{bmatrix}

In [28]:
X = np.array([3, 0, 8, -1]).reshape((2, 2))
X

array([[ 3,  0],
       [ 8, -1]])

In [29]:
l, e = np.linalg.eig(X)
idx = np.argsort(l)[::-1]
l = l[idx]
e = e[:, idx]

Matriz **$\Lambda$**:

In [30]:
L = np.diag(l)
L

array([[ 3.,  0.],
       [ 0., -1.]])

Matriz **$P$**:

In [31]:
P = e
print(P)

[[0.4472136  0.        ]
 [0.89442719 1.        ]]
