In [6]:
import pandas as pd
import numpy as np

# pacotes para obter as distâncias
from scipy.spatial.distance import squareform, pdist
from sklearn.metrics.pairwise import euclidean_distances

pd.options.display.float_format = '{:.2f}'.format    # pandas: para todos os números aparecerem com duas casas decimais
np.set_printoptions(precision=2, suppress=True)      # numpy: para todos os números aparecerem com duas casas decimais

1. Considere a matriz de dados X abaixo (o arquivo .csv está sendo lido a partir de um link onde o arquivo está salvo e o código se encontra abaixo):


In [3]:
matriz = pd.read_csv('https://patriciasiqueira.github.io/arquivos/matrizX.csv', sep=';')
X = matriz.values                          # valores numéricos
X = np.asarray(X, dtype=float)     # transformar em matriz de reais
X

array([[3., 6., 4., 0., 7.],
       [4., 2., 7., 4., 6.],
       [4., 0., 3., 1., 5.],
       [6., 2., 6., 1., 1.],
       [1., 6., 2., 1., 4.],
       [5., 1., 2., 0., 2.],
       [1., 1., 2., 6., 1.],
       [1., 1., 5., 4., 4.],
       [7., 0., 1., 3., 3.],
       [3., 3., 0., 5., 1.]])

In [5]:
X.shape

(10, 5)

In [10]:
# matriz de distâncias
X_dist = squareform(pdist(X, metric='euclidean'))
X_dist

array([[ 0.  ,  6.56,  6.56,  8.12,  4.24,  7.62, 10.25,  7.42,  9.27,
         9.27],
       [ 6.56,  0.  ,  5.48,  6.24,  7.94,  7.68,  8.  ,  4.24,  7.68,
         8.77],
       [ 6.56,  5.48,  0.  ,  5.74,  6.86,  3.61,  7.21,  4.9 ,  4.58,
         7.14],
       [ 8.12,  6.24,  5.74,  0.  ,  8.12,  4.47,  8.19,  6.71,  6.16,
         7.87],
       [ 4.24,  7.94,  6.86,  8.12,  0.  ,  6.78,  7.68,  6.56,  8.83,
         6.48],
       [ 7.62,  7.68,  3.61,  4.47,  6.78,  0.  ,  7.28,  6.71,  4.  ,
         6.16],
       [10.25,  8.  ,  7.21,  8.19,  7.68,  7.28,  0.  ,  4.69,  7.14,
         3.61],
       [ 7.42,  4.24,  4.9 ,  6.71,  6.56,  6.71,  4.69,  0.  ,  7.42,
         6.56],
       [ 9.27,  7.68,  4.58,  6.16,  8.83,  4.  ,  7.14,  7.42,  0.  ,
         5.83],
       [ 9.27,  8.77,  7.14,  7.87,  6.48,  6.16,  3.61,  6.56,  5.83,
         0.  ]])

In [8]:
X_dist.shape

(10, 10)

In [9]:
# matriz de distâncias padronizada
squareform(pdist(X, metric='seuclidean'))

array([[0.  , 2.98, 2.99, 3.73, 1.95, 3.49, 4.7 , 3.4 , 4.25, 4.24],
       [2.98, 0.  , 2.47, 2.88, 3.6 , 3.49, 3.65, 1.96, 3.47, 3.95],
       [2.99, 2.47, 0.  , 2.62, 3.14, 1.66, 3.33, 2.26, 2.12, 3.26],
       [3.73, 2.88, 2.62, 0.  , 3.73, 2.  , 3.77, 3.13, 2.77, 3.56],
       [1.95, 3.6 , 3.14, 3.73, 0.  , 3.13, 3.52, 2.97, 4.09, 2.97],
       [3.49, 3.49, 1.66, 2.  , 3.13, 0.  , 3.38, 3.09, 1.85, 2.83],
       [4.7 , 3.65, 3.33, 3.77, 3.52, 3.38, 0.  , 2.13, 3.34, 1.65],
       [3.4 , 1.96, 2.26, 3.13, 2.97, 3.09, 2.13, 0.  , 3.43, 2.96],
       [4.25, 3.47, 2.12, 2.77, 4.09, 1.85, 3.34, 3.43, 0.  , 2.7 ],
       [4.24, 3.95, 3.26, 3.56, 2.97, 2.83, 1.65, 2.96, 2.7 , 0.  ]])

In [11]:
# usando scipy
squareform(pdist(X, metric='mahalanobis'))

array([[0.  , 2.79, 3.03, 3.74, 1.88, 3.16, 3.73, 3.25, 3.33, 3.2 ],
       [2.79, 0.  , 3.33, 3.4 , 3.69, 3.88, 3.26, 2.62, 3.14, 3.44],
       [3.03, 3.33, 0.  , 3.96, 3.18, 1.95, 3.1 , 2.27, 2.78, 3.67],
       [3.74, 3.4 , 3.96, 0.  , 3.57, 2.77, 3.58, 3.53, 3.83, 3.62],
       [1.88, 3.69, 3.18, 3.57, 0.  , 2.67, 2.84, 2.9 , 3.78, 2.59],
       [3.16, 3.88, 1.95, 2.77, 2.67, 0.  , 2.99, 2.88, 2.85, 3.14],
       [3.73, 3.26, 3.1 , 3.58, 2.84, 2.99, 0.  , 1.82, 3.38, 2.08],
       [3.25, 2.62, 2.27, 3.53, 2.9 , 2.88, 1.82, 0.  , 3.73, 3.34],
       [3.33, 3.14, 2.78, 3.83, 3.78, 2.85, 3.38, 3.73, 0.  , 2.52],
       [3.2 , 3.44, 3.67, 3.62, 2.59, 3.14, 2.08, 3.34, 2.52, 0.  ]])

In [15]:
np.corrcoef(X.T)

array([[ 1.  , -0.4 ,  0.05, -0.35, -0.12],
       [-0.4 ,  1.  ,  0.01, -0.33,  0.35],
       [ 0.05,  0.01,  1.  , -0.14,  0.44],
       [-0.35, -0.33, -0.14,  1.  , -0.35],
       [-0.12,  0.35,  0.44, -0.35,  1.  ]])

2. Vamos criar um conjunto de dados que mostra as informações sobre 20 estudantes: a nota na prova, o número de horas estudadas e seu coeficiente acadêmico. Os códigos para fazer isso no python estão abaixo (copie e coe no colab)

In [16]:
# criando um dicionário de dados
dados = {
        'nome': ['Paula', 'Juliana', 'Felipe', 'Joana', 'Tales', 'João', 'Fabiana', 'Rui', 'Ana', 'Melissa', 'Miguel', 'Luiz', 'Marta', 'Joana', 'Bia', 'Júlia', 'Letícia', 'Iago', 'Flávia', 'Maria'],
        'nota': [9.1, 9.3, 7.2, 8.7, 8.6, 7.3, 6.8, 8.7, 7.8, 9.9, 9.5, 7.6, 8.4, 9.6, 7.6, 8.0, 8.3, 8.4, 7.3, 7.4],
        'horas': [16, 6, 3, 10, 12, 3, 2, 15, 2, 15, 9, 10, 4, 13, 3, 3, 4, 3, 4, 4],
        'ca': [7.0, 8.8, 8.0, 8.3, 8.8, 8.4, 7.8, 9.4, 9.0, 9.3, 8.9, 8.2, 9.5, 9.4, 8.1, 9.3, 9.3, 9.0, 8.9, 8.9]
        }

# transformar em dataframe
df = pd.DataFrame(dados, columns=['nome', 'nota', 'horas', 'ca'])
df

nome  nota  horas   ca
0     Paula  9.10     16 7.00
1   Juliana  9.30      6 8.80
2    Felipe  7.20      3 8.00
3     Joana  8.70     10 8.30
4     Tales  8.60     12 8.80
5      João  7.30      3 8.40
6   Fabiana  6.80      2 7.80
7       Rui  8.70     15 9.40
8       Ana  7.80      2 9.00
9   Melissa  9.90     15 9.30
10   Miguel  9.50      9 8.90
11     Luiz  7.60     10 8.20
12    Marta  8.40      4 9.50
13    Joana  9.60     13 9.40
14      Bia  7.60      3 8.10
15    Júlia  8.00      3 9.30
16  Letícia  8.30      4 9.30
17     Iago  8.40      3 9.00
18   Flávia  7.30      4 8.90
19    Maria  7.40      4 8.90

In [18]:
df[['nota', 'horas', 'ca']].corr()

nota  horas    ca
nota   1.00   0.72  0.32
horas  0.72   1.00 -0.04
ca     0.32  -0.04  1.00

3. Seja a matriz de dados X derivada do dataframe:

In [19]:
# subselecionar variáveis e transformar em matriz
X = df.values[:, 1:]
X = np.asarray(X, dtype=float)
X

array([[ 9.1, 16. ,  7. ],
       [ 9.3,  6. ,  8.8],
       [ 7.2,  3. ,  8. ],
       [ 8.7, 10. ,  8.3],
       [ 8.6, 12. ,  8.8],
       [ 7.3,  3. ,  8.4],
       [ 6.8,  2. ,  7.8],
       [ 8.7, 15. ,  9.4],
       [ 7.8,  2. ,  9. ],
       [ 9.9, 15. ,  9.3],
       [ 9.5,  9. ,  8.9],
       [ 7.6, 10. ,  8.2],
       [ 8.4,  4. ,  9.5],
       [ 9.6, 13. ,  9.4],
       [ 7.6,  3. ,  8.1],
       [ 8. ,  3. ,  9.3],
       [ 8.3,  4. ,  9.3],
       [ 8.4,  3. ,  9. ],
       [ 7.3,  4. ,  8.9],
       [ 7.4,  4. ,  8.9]])

In [20]:
X.shape

(20, 3)

In [21]:
De = squareform(pdist(X, metric='euclidean'))
Dep = squareform(pdist(X, metric='seuclidean'))
Dm = squareform(pdist(X, metric='mahalanobis'))

In [22]:
def compara_dist(df, op='max'):
    if op == 'max':
        maximo = np.amax(df.values)
        a = np.where(df.values == maximo)
        valor = maximo
    else:
        df = df[df > 0]
        minimo = np.nanmin(df.values)
        a = np.where(df.values == minimo)
        valor = minimo
    return [df.index[a[0][0]], df.index[a[0][1]], round(valor, 2)]

In [23]:
Dedf = pd.DataFrame(De, index=df.nome, columns=df.nome)    # distância euclidiana
Depdf = pd.DataFrame(Dep, index=df.nome, columns=df.nome)   # distância euclidiana padronizada
Dmdf = pd.DataFrame(Dm, index=df.nome, columns=df.nome)     # mahalanobis

In [24]:
# alunos mais semelhantes usando dedf
compara_dist(Dedf, 'min')

['Flávia', 'Maria', np.float64(0.1)]

In [25]:
# alunos mais distantes usando dedf
compara_dist(Dedf)

['Paula', 'Fabiana', np.float64(14.21)]

In [26]:
# alunos mais semelhantes usando depdf
compara_dist(Depdf, 'min')

['Flávia', 'Maria', np.float64(0.11)]

In [27]:
# alunos mais distantes usando depdf
compara_dist(Depdf)

['Fabiana', 'Melissa', np.float64(4.92)]

In [28]:
# alunos mais semelhantes usando dmdf
compara_dist(Dmdf, 'min')

['Flávia', 'Maria', np.float64(0.19)]

In [29]:
# alunos mais distantes usando dmdf
compara_dist(Dmdf)

['Paula', 'Rui', np.float64(4.54)]

In [37]:
df

nome  nota  horas   ca
0     Paula  9.10     16 7.00
1   Juliana  9.30      6 8.80
2    Felipe  7.20      3 8.00
3     Joana  8.70     10 8.30
4     Tales  8.60     12 8.80
5      João  7.30      3 8.40
6   Fabiana  6.80      2 7.80
7       Rui  8.70     15 9.40
8       Ana  7.80      2 9.00
9   Melissa  9.90     15 9.30
10   Miguel  9.50      9 8.90
11     Luiz  7.60     10 8.20
12    Marta  8.40      4 9.50
13    Joana  9.60     13 9.40
14      Bia  7.60      3 8.10
15    Júlia  8.00      3 9.30
16  Letícia  8.30      4 9.30
17     Iago  8.40      3 9.00
18   Flávia  7.30      4 8.90
19    Maria  7.40      4 8.90