In [15]:
import pandas as pd
import numpy as np
import seaborn as sns

sns.set(style='whitegrid')
from sklearn.decomposition import PCA
from sklearn.preprocessing import scale

In [16]:
S = np.array([[5, 2], [2, 2]])
S

array([[5, 2],
       [2, 2]])

In [17]:
l, e = np.linalg.eig(S)
idx = np.argsort(l)[::-1]
l = l[idx]
e = e[:,idx]
print(l)

[6. 1.]


In [18]:
print(e)

[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]


In [24]:
np.sum(l)

np.float64(7.0)

In [22]:
np.trace(S) == np.sum(l)

np.True_

In [46]:
l[0] / np.sum(l)

np.float64(0.8571428571428571)

In [40]:
e[:, 0].T @ e[:, 0], e[:, 1].T @ e[:, 1]

(np.float64(0.9999999999999999), np.float64(0.9999999999999999))

In [44]:
e[:, 1].T @ e[:, 0]

np.float64(0.0)

In [45]:
# calcular a correlação entre as duas variáveis
r12 = S[0,1] / (S[0, 0] * S[1, 1]) ** 0.5

# montar a matriz de correlações amostrais
R = np.array([[1, r12], [r12, 1]])
R


array([[1.        , 0.63245553],
       [0.63245553, 1.        ]])

In [47]:
l, e = np.linalg.eig(R)
idx = np.argsort(l)[::-1]
l = l[idx]
e = e[:,idx]
print(l)
print(e)

[1.63245553 0.36754447]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [48]:
l[0] / np.sum(l)

np.float64(0.816227766016838)