In [1]:
import pandas as pd
import numpy as np

In [2]:
S = np.array([7.64, 2.87, 7.04, 2.87, 37.59, 35.70, 7.04, 35.70, 44]).reshape((3, 3))
S

array([[ 7.64,  2.87,  7.04],
       [ 2.87, 37.59, 35.7 ],
       [ 7.04, 35.7 , 44.  ]])

In [14]:
np.var(S, axis=1)

array([  4.5002    , 254.09548889, 250.70302222])

In [28]:
l, e = np.linalg.eig(S)
idx = np.argsort(l)[::-1]
l = l[idx]
e = e[:, idx]
print(l)
print(e)

[77.36912635  8.72622173  3.13465193]
[[-0.10189349 -0.81725315 -0.56719926]
 [-0.66850338  0.47848935 -0.56934275]
 [-0.73669597 -0.3211623   0.59509145]]


In [18]:
trace = sum(l)
trace

np.float64(89.22999999999995)

In [23]:
np.trace(S)

np.float64(89.23)

In [19]:
np.allclose(np.trace(S), trace)

True

In [30]:
l[0] * l[1] * l[2]

np.float64(2116.329375999998)

In [20]:
np.linalg.det(S)

np.float64(2116.329376000001)

In [31]:
b = np.array([-1, 3, 9, -7]).reshape((2, 2))
b

array([[-1,  3],
       [ 9, -7]])

In [33]:
l, e = np.linalg.eig(b)
l

array([  2., -10.])

In [32]:
l, e = np.linalg.eig(b)
idx = np.argsort(l)[::-1]
l = l[idx]
e = e[:, idx]
print(l)
print(e)

[  2. -10.]
[[ 0.70710678 -0.31622777]
 [ 0.70710678  0.9486833 ]]
