## Word Embedding Techniques using Embedding Layer in Keras

In [2]:
### Libraries used Tensorflow > 2.0 and Keras
import numpy as np

import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import Input
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

print(tf.__version__)

2.9.1


In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Vocabulary size
voc_size = 500

### One Hot Representation

In [5]:
one_hot_repr = [one_hot(words, voc_size) for words in sent]
print(one_hot_repr)

[[15, 190, 99, 19], [15, 190, 99, 102], [15, 233, 99, 129], [194, 282, 252, 13, 11], [194, 282, 252, 13, 282], [422, 15, 25, 99, 421], [119, 258, 117, 13]]


### Word Embedding Representation

In [6]:
## pre pading
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding="pre", maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0  15 190  99  19]
 [  0   0   0   0  15 190  99 102]
 [  0   0   0   0  15 233  99 129]
 [  0   0   0 194 282 252  13  11]
 [  0   0   0 194 282 252  13 282]
 [  0   0   0 422  15  25  99 421]
 [  0   0   0   0 119 258 117  13]]


In [7]:
## 10 feature dimensions
dim = 10

In [8]:
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [9]:
## "the glass of milk"
embedded_docs[0]

array([  0,   0,   0,   0,  15, 190,  99,  19])

In [10]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 136ms/step


array([[-0.03611733,  0.02915761,  0.00326975, -0.04671866, -0.01129211,
        -0.02177311, -0.03593468,  0.04195067, -0.01710625, -0.04313778],
       [-0.03611733,  0.02915761,  0.00326975, -0.04671866, -0.01129211,
        -0.02177311, -0.03593468,  0.04195067, -0.01710625, -0.04313778],
       [-0.03611733,  0.02915761,  0.00326975, -0.04671866, -0.01129211,
        -0.02177311, -0.03593468,  0.04195067, -0.01710625, -0.04313778],
       [-0.03611733,  0.02915761,  0.00326975, -0.04671866, -0.01129211,
        -0.02177311, -0.03593468,  0.04195067, -0.01710625, -0.04313778],
       [-0.02994334, -0.01358159,  0.04053667,  0.01019569,  0.03716693,
         0.04119015,  0.049212  ,  0.04843136, -0.01219583,  0.02202605],
       [-0.0241388 , -0.00855054,  0.04701408, -0.02643153,  0.04053856,
        -0.04300989, -0.02631006, -0.01005584, -0.04359517,  0.00297047],
       [-0.01246744, -0.02971818, -0.01459314,  0.02737241,  0.03136139,
         0.02921854,  0.03686709,  0.00905712

In [11]:
embedded_docs.shape

(7, 8)

In [12]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 25ms/step


array([[[-0.03611733,  0.02915761,  0.00326975, -0.04671866,
         -0.01129211, -0.02177311, -0.03593468,  0.04195067,
         -0.01710625, -0.04313778],
        [-0.03611733,  0.02915761,  0.00326975, -0.04671866,
         -0.01129211, -0.02177311, -0.03593468,  0.04195067,
         -0.01710625, -0.04313778],
        [-0.03611733,  0.02915761,  0.00326975, -0.04671866,
         -0.01129211, -0.02177311, -0.03593468,  0.04195067,
         -0.01710625, -0.04313778],
        [-0.03611733,  0.02915761,  0.00326975, -0.04671866,
         -0.01129211, -0.02177311, -0.03593468,  0.04195067,
         -0.01710625, -0.04313778],
        [-0.02994334, -0.01358159,  0.04053667,  0.01019569,
          0.03716693,  0.04119015,  0.049212  ,  0.04843136,
         -0.01219583,  0.02202605],
        [-0.0241388 , -0.00855054,  0.04701408, -0.02643153,
          0.04053856, -0.04300989, -0.02631006, -0.01005584,
         -0.04359517,  0.00297047],
        [-0.01246744, -0.02971818, -0.01459314,  0.0